// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v6.33.4
// source: pb/vectordb.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type InsertRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Vector        []float32              `protobuf:"fixed32,1,rep,packed,name=vector,proto3" json:"vector,omitempty"` // 'repeated float' maps to Go's []float32
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *InsertRequest) Reset() {
	*x = InsertRequest{}
	mi := &file_pb_vectordb_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *InsertRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*InsertRequest) ProtoMessage() {}

func (x *InsertRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pb_vectordb_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use InsertRequest.ProtoReflect.Descriptor instead.
func (*InsertRequest) Descriptor() ([]byte, []int) {
	return file_pb_vectordb_proto_rawDescGZIP(), []int{0}
}

func (x *InsertRequest) GetVector() []float32 {
	if x != nil {
		return x.Vector
	}
	return nil
}

type InsertResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *InsertResponse) Reset() {
	*x = InsertResponse{}
	mi := &file_pb_vectordb_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *InsertResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*InsertResponse) ProtoMessage() {}

func (x *InsertResponse) ProtoReflect() protoreflect.Message {
	mi := &file_pb_vectordb_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use InsertResponse.ProtoReflect.Descriptor instead.
func (*InsertResponse) Descriptor() ([]byte, []int) {
	return file_pb_vectordb_proto_rawDescGZIP(), []int{1}
}

func (x *InsertResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

type SearchRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Query         []float32              `protobuf:"fixed32,1,rep,packed,name=query,proto3" json:"query,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SearchRequest) Reset() {
	*x = SearchRequest{}
	mi := &file_pb_vectordb_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SearchRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SearchRequest) ProtoMessage() {}

func (x *SearchRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pb_vectordb_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SearchRequest.ProtoReflect.Descriptor instead.
func (*SearchRequest) Descriptor() ([]byte, []int) {
	return file_pb_vectordb_proto_rawDescGZIP(), []int{2}
}

func (x *SearchRequest) GetQuery() []float32 {
	if x != nil {
		return x.Query
	}
	return nil
}

type SearchResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	NearestVector []float32              `protobuf:"fixed32,1,rep,packed,name=nearest_vector,json=nearestVector,proto3" json:"nearest_vector,omitempty"`
	Distance      float32                `protobuf:"fixed32,2,opt,name=distance,proto3" json:"distance,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SearchResponse) Reset() {
	*x = SearchResponse{}
	mi := &file_pb_vectordb_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SearchResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SearchResponse) ProtoMessage() {}

func (x *SearchResponse) ProtoReflect() protoreflect.Message {
	mi := &file_pb_vectordb_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SearchResponse.ProtoReflect.Descriptor instead.
func (*SearchResponse) Descriptor() ([]byte, []int) {
	return file_pb_vectordb_proto_rawDescGZIP(), []int{3}
}

func (x *SearchResponse) GetNearestVector() []float32 {
	if x != nil {
		return x.NearestVector
	}
	return nil
}

func (x *SearchResponse) GetDistance() float32 {
	if x != nil {
		return x.Distance
	}
	return 0
}

// Request to fetch node statistics (empty because we just need to trigger it)
type StatsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StatsRequest) Reset() {
	*x = StatsRequest{}
	mi := &file_pb_vectordb_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StatsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StatsRequest) ProtoMessage() {}

func (x *StatsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pb_vectordb_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StatsRequest.ProtoReflect.Descriptor instead.
func (*StatsRequest) Descriptor() ([]byte, []int) {
	return file_pb_vectordb_proto_rawDescGZIP(), []int{4}
}

// Response containing the size of the node's vector database
type StatsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Count         int64                  `protobuf:"varint,1,opt,name=count,proto3" json:"count,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StatsResponse) Reset() {
	*x = StatsResponse{}
	mi := &file_pb_vectordb_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StatsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StatsResponse) ProtoMessage() {}

func (x *StatsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_pb_vectordb_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StatsResponse.ProtoReflect.Descriptor instead.
func (*StatsResponse) Descriptor() ([]byte, []int) {
	return file_pb_vectordb_proto_rawDescGZIP(), []int{5}
}

func (x *StatsResponse) GetCount() int64 {
	if x != nil {
		return x.Count
	}
	return 0
}

var File_pb_vectordb_proto protoreflect.FileDescriptor

const file_pb_vectordb_proto_rawDesc = "" +
	"\n" +
	"\x11pb/vectordb.proto\x12\bvectordb\"'\n" +
	"\rInsertRequest\x12\x16\n" +
	"\x06vector\x18\x01 \x03(\x02R\x06vector\"*\n" +
	"\x0eInsertResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\"%\n" +
	"\rSearchRequest\x12\x14\n" +
	"\x05query\x18\x01 \x03(\x02R\x05query\"S\n" +
	"\x0eSearchResponse\x12%\n" +
	"\x0enearest_vector\x18\x01 \x03(\x02R\rnearestVector\x12\x1a\n" +
	"\bdistance\x18\x02 \x01(\x02R\bdistance\"\x0e\n" +
	"\fStatsRequest\"%\n" +
	"\rStatsResponse\x12\x14\n" +
	"\x05count\x18\x01 \x01(\x03R\x05count2\xc6\x01\n" +
	"\rVectorService\x12;\n" +
	"\x06Insert\x12\x17.vectordb.InsertRequest\x1a\x18.vectordb.InsertResponse\x12;\n" +
	"\x06Search\x12\x17.vectordb.SearchRequest\x1a\x18.vectordb.SearchResponse\x12;\n" +
	"\bGetStats\x12\x16.vectordb.StatsRequest\x1a\x17.vectordb.StatsResponseB\x06Z\x04./pbb\x06proto3"

var (
	file_pb_vectordb_proto_rawDescOnce sync.Once
	file_pb_vectordb_proto_rawDescData []byte
)

func file_pb_vectordb_proto_rawDescGZIP() []byte {
	file_pb_vectordb_proto_rawDescOnce.Do(func() {
		file_pb_vectordb_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_pb_vectordb_proto_rawDesc), len(file_pb_vectordb_proto_rawDesc)))
	})
	return file_pb_vectordb_proto_rawDescData
}

var file_pb_vectordb_proto_msgTypes = make([]protoimpl.MessageInfo, 6)
var file_pb_vectordb_proto_goTypes = []any{
	(*InsertRequest)(nil),  // 0: vectordb.InsertRequest
	(*InsertResponse)(nil), // 1: vectordb.InsertResponse
	(*SearchRequest)(nil),  // 2: vectordb.SearchRequest
	(*SearchResponse)(nil), // 3: vectordb.SearchResponse
	(*StatsRequest)(nil),   // 4: vectordb.StatsRequest
	(*StatsResponse)(nil),  // 5: vectordb.StatsResponse
}
var file_pb_vectordb_proto_depIdxs = []int32{
	0, // 0: vectordb.VectorService.Insert:input_type -> vectordb.InsertRequest
	2, // 1: vectordb.VectorService.Search:input_type -> vectordb.SearchRequest
	4, // 2: vectordb.VectorService.GetStats:input_type -> vectordb.StatsRequest
	1, // 3: vectordb.VectorService.Insert:output_type -> vectordb.InsertResponse
	3, // 4: vectordb.VectorService.Search:output_type -> vectordb.SearchResponse
	5, // 5: vectordb.VectorService.GetStats:output_type -> vectordb.StatsResponse
	3, // [3:6] is the sub-list for method output_type
	0, // [0:3] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_pb_vectordb_proto_init() }
func file_pb_vectordb_proto_init() {
	if File_pb_vectordb_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_pb_vectordb_proto_rawDesc), len(file_pb_vectordb_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   6,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_pb_vectordb_proto_goTypes,
		DependencyIndexes: file_pb_vectordb_proto_depIdxs,
		MessageInfos:      file_pb_vectordb_proto_msgTypes,
	}.Build()
	File_pb_vectordb_proto = out.File
	file_pb_vectordb_proto_goTypes = nil
	file_pb_vectordb_proto_depIdxs = nil
}
