FROM golang:alpine AS builder
WORKDIR /app
COPY go.mod go.sum ./
RUN go mod download
COPY . .
# Skip go mod tidy here! Use direct build with native flags
RUN CGO_ENABLED=0 GOOS=linux GOARCH=arm64 go build -o vector-worker .

FROM alpine:latest
WORKDIR /root/
COPY --from=builder /app/vector-worker .
EXPOSE 50051
CMD ["./vector-worker"]