# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: vectordb.proto
# Protobuf Python Version: 7.35.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    7,
    35,
    0,
    '',
    'vectordb.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0evectordb.proto\x12\x08vectordb\"\x1f\n\rInsertRequest\x12\x0e\n\x06vector\x18\x01 \x03(\x02\"!\n\x0eInsertResponse\x12\x0f\n\x07success\x18\x01 \x01(\x08\"\x1e\n\rSearchRequest\x12\r\n\x05query\x18\x01 \x03(\x02\":\n\x0eSearchResponse\x12\x16\n\x0enearest_vector\x18\x01 \x03(\x02\x12\x10\n\x08\x64istance\x18\x02 \x01(\x02\x32\x89\x01\n\rVectorService\x12;\n\x06Insert\x12\x17.vectordb.InsertRequest\x1a\x18.vectordb.InsertResponse\x12;\n\x06Search\x12\x17.vectordb.SearchRequest\x1a\x18.vectordb.SearchResponseB\x06Z\x04./pbb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'vectordb_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'Z\004./pb'
  _globals['_INSERTREQUEST']._serialized_start=28
  _globals['_INSERTREQUEST']._serialized_end=59
  _globals['_INSERTRESPONSE']._serialized_start=61
  _globals['_INSERTRESPONSE']._serialized_end=94
  _globals['_SEARCHREQUEST']._serialized_start=96
  _globals['_SEARCHREQUEST']._serialized_end=126
  _globals['_SEARCHRESPONSE']._serialized_start=128
  _globals['_SEARCHRESPONSE']._serialized_end=186
  _globals['_VECTORSERVICE']._serialized_start=189
  _globals['_VECTORSERVICE']._serialized_end=326
# @@protoc_insertion_point(module_scope)
